channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - compas
  - compas_fab
  - pip
  - pip:
    # code style tools
    - flake8
    - autopep8
    - pylint
    - isort
    # testing tools
    - pytest
    - ironpython-pytest
    # autocomplete for Rhino
    - Rhino-stubs
    - Grasshopper-stubs
