version: '2'
services:
  ros-master:
    image: augmentedfabricationlab/robarch-2024:latest
    container_name: ros-master
    ports:
      - "11311:11311"
    command:
      - roscore

  ros-bridge:
    image: augmentedfabricationlab/robarch-2024:latest
    container_name: ros-bridge
    environment:
      - "ROS_HOSTNAME=ros-bridge"
      - "ROS_MASTER_URI=http://ros-master:11311"
    ports:
      - "9090:9090"
    depends_on:
      - ros-master
    command:
      - roslaunch
      - --wait
      - rosbridge_server
      - rosbridge_websocket.launch

  ros-fileserver:
    image: augmentedfabricationlab/robarch-2024:latest
    container_name: ros-fileserver
    environment:
      - ROS_HOSTNAME=ros-fileserver
      - ROS_MASTER_URI=http://ros-master:11311
    depends_on:
      - ros-master
    command:
      - roslaunch
      - --wait
      - file_server
      - file_server.launch

  # robot:
  #   image: augmentedfabricationlab/robarch-2024:latest
  #   container_name: robot
  #   environment:
  #     - ROS_HOSTNAME=robot
  #     - ROS_MASTER_URI=http://ros-master:11311
  #   depends_on:
  #     - ros-master
  #   command:
  #     - roslaunch
  #     - --wait
  #     - robarch_launcher
  #     - robot.launch
  #     - robot_ip := 192.168.0.200
  #     - kinematics_file := /root/my_robot_calibration.yaml

  robot-demo:
    image: augmentedfabricationlab/robarch-2024:latest
    container_name: robot-demo
    environment:
      - ROS_HOSTNAME=robot-demo
      - ROS_MASTER_URI=http://ros-master:11311
    depends_on:
      - ros-master
    command:
      - roslaunch
      - --wait
      - ur10e_mobilecart_liftkit_600mm_moveit_config
      - demo.launch
      - use_rviz:=false