version: '2'
services:
  ros-master:
    image: augmentedfabricationlab/robarch-2024:latest
    container_name: ros-master
    ports:
      - "11311:11311"
    command:
      - roscore

  ros-bridge:
    image: augmentedfabricationlab/robarch-2024:latest
    container_name: ros-bridge
    environment:
      - "ROS_HOSTNAME=ros-bridge"
      - "ROS_MASTER_URI=http://ros-master:11311"
    ports:
      - "9090:9090"
    depends_on:
      - ros-master
    command:
      - roslaunch
      - --wait
      - rosbridge_server
      - rosbridge_websocket.launch

  ros-fileserver:
    image: augmentedfabricationlab/robarch-2024:latest
    container_name: ros-fileserver
    environment:
      - ROS_HOSTNAME=ros-fileserver
      - ROS_MASTER_URI=http://ros-master:11311
    depends_on:
      - ros-master
    command:
      - roslaunch
      - --wait
      - file_server
      - file_server.launch

  robot:
    image: augmentedfabricationlab/robarch-2024:latest
    container_name: robot
    environment:
      - ROS_HOSTNAME=robot
      - ROS_MASTER_URI=http://ros-master:11311
    depends_on:
      - ros-master
    command:
      - roslaunch
      - --wait
      - robarch_launcher
      - robot.launch
      - robot_ip := 192.168.0.200
      - kinematics_file := /root/my_robot_calibration.yaml
  
  marker-tracking:
    image: augmentedfabricationlab/robarch-2024:latest
    container_name: marker-tracking
    environment:
      - ROS_HOSTNAME=marker-tracking
      - ROS_MASTER_URI=http://ros-master:11311
    depends_on:
      - ros-master
    command:
      - roslaunch
      - --wait
      - robarch_launcher
      - marker_tracking.launch
      - dictionary := DICT_7X7_250
      - marker_size := 0.07