# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Collaborative Augmented Assembly: Task Distribution in Human-Robot Collaborative Assembly with Phone-based Augmented Reality
tagline:          'RobArch 2024'
description:      'Workshop'
baseurl: "/robarch24/" # the subpath of your site, e.g. /blog
url: "https://intuitiverobotics-augmentedtechnologies.github.io/robarch24/" # the base hostname & protocol for your site, e.g. http://example.com

paginate:         5

# Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/IntuitiveRobotics-AugmentedTechnologies/robarch24

plugins:
  - jekyll-feed

collections:
  sessions:
    output: true
