controller_list:
  - name: fake_ur10e_and_liftkit_controller
    type: $(arg fake_execution_type)
    joints:
      - liftkit_joint
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_ur10e_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
initial:  # Define initial robot poses per group
#  - group: ur10e_and_liftkit
#    pose: home

  []